server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Serve all static files directly
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the GraphQL server
    location /graphql {
        proxy_pass http://graphql-api:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Serve the settings.js file directly
    location /settings.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
        try_files $uri =404;
    }

    # Redirect 404 errors to index.html for SPA
    error_page 404 =200 /index.html;
} 